 
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-worker-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
      - name: ng-control
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 22222
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: udp-worker-rtpengine-ng
      - name: rtp-a
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 19000
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: worker-rtp-a
      - name: rtcp-a
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 19001
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: worker-rtcp-a
      - name: rtp-b
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 19002
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: worker-rtp-b
      - name: rtcp-b
        reuse_port: true
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 19003
        listener_filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: worker-rtcp-b
      clusters:
      - name: udp-worker-rtpengine-ng
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_udp
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 22224
      - name: worker-rtp-a
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_udp
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    #offer modified sdp rtp port for user A
                    port_value: 19500
      - name: worker-rtcp-a
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_udp
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    #offer modified sdp rtcp port for user A
                    port_value: 19501
      - name: worker-rtp-b
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_udp
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    #offer modified sdp rtp port for user B
                    port_value: 19502
      - name: worker-rtcp-b
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_udp
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    #offer modified sdp rtcp port for user B
                    port_value: 19503
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtpengine-config
  namespace: default
data:
  rtpengine.conf: |
    [rtpengine]
    # access only via the sidecar proxy
    # listen-ng=MY_IP:22222
    # interface=MY_IP
    listen-ng=127.0.0.1:22224
    interface=lo
    foreground=true
    log-stderr=true
    port-min=10000
    port-max=20000
    recording-dir=/tmp
    recording-method=pcap
    recording-format=eth
    log-level=7
    delete-delay=0
    timeout=3600
    # redis = 127.0.0.1:6379/5
    # redis-write = password@12.23.34.45:6379/42
    # redis-num-threads = 8
    # no-redis-required = false
    # redis-expires = 86400
    # redis-allowed-errors = -1
    # redis-disable-time = 10
    # redis-cmd-timeout = 0
    # redis-connect-timeout = 1000
    # sip-source = false
    # dtls-passive = false
---

# worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-worker
  labels:
    app: envoy-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-worker
  template:
    metadata:
      labels:
        app: envoy-worker
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-worker-config
        - name: rtpengine-config-volume
          configMap:
            name: rtpengine-config
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
      containers:
      # sidecar
      - name: envoy-worker
        image: envoyproxy/envoy:v1.17-latest
        imagePullPolicy: Always
        #command: [ "envoy" ]
        #args: ["-c", "/etc/envoy/envoy.yaml", "-l", "trace"]
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
          - containerPort: 9901
            name: web
          - containerPort: 22222
            name: udp-listener
        volumeMounts:
          - name: envoy-config-volume
            mountPath: /etc/envoy
      #- name: net-debug
        #image: retvari/net-debug:latest
        #imagePullPolicy: IfNotPresent
        #ports:
          #- containerPort: 1236
            #name: net-debug
      - name: rtpengine
        image: drachtio/rtpengine
        imagePullPolicy: IfNotPresent
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        command: [ "/usr/local/bin/rtpengine" ]
        args: [ "--config-file=/etc/rtpengine/rtpengine.conf", "-i", "lo", "-f", "-L", "7", "-E" ]
        volumeMounts:
          - name: rtpengine-config-volume
            mountPath: /etc/rtpengine

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy-worker
  name: envoy-worker
spec:
  ports:
  - port: 19000
    name: worker-rtp-a-service-port
    protocol: UDP
    targetPort: 19000
  - port: 19001
    name: worker-rtcp-a-service-port
    protocol: UDP
    targetPort: 19001
  - port: 19002
    name: worker-rtp-b-service-port
    protocol: UDP
    targetPort: 19002
  - port: 19003
    name: worker-rtcp-b-service-port
    protocol: UDP
    targetPort: 19003
  - port: 22222
    name: udp-rtpengine-ng-port
    protocol: UDP
    targetPort: 22222
  selector:
    app: envoy-worker
  type: ClusterIP
